// Package closing builds what `vloop brief close` writes: the brief's run
// record and the frozen metrics snapshot.
package closing

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/mvelosop/vloop/internal/defect"
	"github.com/mvelosop/vloop/internal/metrics"
)

const (
	// Begin and End are the marker lines around the generated run record.
	Begin = "<!-- vloop:run-record:begin -->"
	End   = "<!-- vloop:run-record:end -->"
)

// PutRunRecord puts record between the marker lines of doc, replacing what is
// there; without markers it appends the block. Bytes outside the markers are
// never touched. record should end in a newline.
func PutRunRecord(doc, record string) string {
	if !strings.HasSuffix(record, "\n") {
		record += "\n"
	}
	if b, e, ok := findMarkers(doc); ok {
		return doc[:b] + record + doc[e:]
	}
	if doc != "" && !strings.HasSuffix(doc, "\n") {
		doc += "\n"
	}
	return doc + Begin + "\n" + record + End + "\n"
}

// findMarkers returns the offset just after the begin line and the offset of
// the end line that follows it.
func findMarkers(doc string) (int, int, bool) {
	begin := -1
	for off := 0; off < len(doc); {
		line, next := doc[off:], len(doc)
		if i := strings.IndexByte(line, '\n'); i >= 0 {
			line, next = line[:i], off+i+1
		}
		line = strings.TrimRight(line, " \t\r")
		switch {
		case begin < 0 && line == Begin:
			begin = next
		case begin >= 0 && line == End:
			return begin, off, true
		}
		off = next
	}
	return 0, 0, false
}

// Record is what the run record is rendered from.
type Record struct {
	Name     string // the brief's name, e.g. B20260101-0900-a.loop-brief
	Date     time.Time
	Report   *metrics.Report
	Derived  []metrics.Derived
	Recorded []defect.Defect
}

// Render is the run record, without the markers.
func Render(r Record) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## Run record\n\nGenerated by vloop brief close on %s. Recompute with: vloop metrics %s\n\n",
		r.Date.Format("2006-01-02"), r.Name)
	fence := func(print func(w *bytes.Buffer)) {
		var buf bytes.Buffer
		print(&buf)
		b.WriteString("```\n" + buf.String() + "```\n\n")
	}
	fence(func(w *bytes.Buffer) { metrics.PrintSummary(w, r.Report) })
	fence(func(w *bytes.Buffer) { metrics.PrintByTask(w, r.Report) })

	ds := append([]metrics.Derived(nil), r.Derived...)
	sort.SliceStable(ds, func(i, j int) bool { return ds[i].Iteration < ds[j].Iteration })
	ids := metrics.DerivedIDs(r.Report.RunID, ds)
	for i, d := range ds {
		line(&b, ids[i], d.Kind, d.Origin, d.FoundBy, d.Summary)
	}
	rec := append([]defect.Defect(nil), r.Recorded...)
	sort.SliceStable(rec, func(i, j int) bool { return rec[i].ID < rec[j].ID })
	for _, d := range rec {
		line(&b, d.ID, d.Kind, d.Origin, d.FoundBy, d.Summary)
	}
	return b.String()
}

func line(b *strings.Builder, id, kind, origin, foundBy, summary string) {
	fmt.Fprintf(b, "- %s — %s, %s, found by %s: %s\n", id, kind, origin, foundBy, summary)
}

// SnapshotDir is where snapshots live, repo-relative.
const SnapshotDir = ".vloop/state/metrics"

// WriteSnapshot saves r as `.vloop/state/metrics/<run id>.json` under root and
// returns the repo-relative path with `/` separators.
func WriteSnapshot(root string, r *metrics.Report) (string, error) {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return "", err
	}
	rel := path.Join(SnapshotDir, r.RunID+".json")
	full := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(full, append(data, '\n'), 0o644); err != nil {
		return "", err
	}
	return rel, nil
}
