package closing

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/mvelosop/vloop/internal/defect"
	"github.com/mvelosop/vloop/internal/metrics"
	"github.com/mvelosop/vloop/internal/schema"
)

func fixtureReport(t *testing.T) *metrics.Report {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "schema", "testdata", "metrics.valid.json"))
	if err != nil {
		t.Fatal(err)
	}
	var r metrics.Report
	if err := json.Unmarshal(data, &r); err != nil {
		t.Fatal(err)
	}
	return &r
}

func TestRunRecordAppend(t *testing.T) {
	doc := "# Brief\nno final newline"
	got := PutRunRecord(doc, "rec\n")
	want := doc + "\n" + Begin + "\nrec\n" + End + "\n"
	if got != want {
		t.Fatalf("got %q want %q", got, want)
	}
	if got := PutRunRecord("", "rec\n"); got != Begin+"\nrec\n"+End+"\n" {
		t.Fatalf("empty doc: %q", got)
	}
}

func TestRunRecordReplaceKeepsOutside(t *testing.T) {
	head := "head  \n" + Begin + "\n"
	tail := End + "  \nafter  \nno final newline"
	got := PutRunRecord(head+"old\nold2\n"+tail, "new\n")
	if got != head+"new\n"+tail {
		t.Fatalf("got %q", got)
	}
	// an end marker before the begin marker is not a pair
	doc := End + "\n" + Begin + "\nx\n"
	if got := PutRunRecord(doc, "r\n"); !strings.HasPrefix(got, doc+Begin+"\nr\n") {
		t.Fatalf("got %q", got)
	}
}

func TestRunRecordIdempotent(t *testing.T) {
	once := PutRunRecord("# B\n", "rec\n")
	if twice := PutRunRecord(once, "rec\n"); twice != once {
		t.Fatalf("not idempotent: %q", twice)
	}
}

func TestRunRecordRendered(t *testing.T) {
	r := fixtureReport(t)
	r.RunID = "B1"
	got := Render(Record{
		Name:   "B1.loop-brief",
		Date:   time.Date(2026, 1, 2, 0, 0, 0, 0, time.UTC),
		Report: r,
		Derived: []metrics.Derived{
			{Task: "T2", Iteration: 3, Origin: "work", Kind: "bug", FoundBy: "review", Summary: "b"},
			{Task: "T1", Iteration: 2, Origin: "work", Kind: "bug", FoundBy: "gate", Summary: "gate failed"},
			{Task: "T2", Iteration: 3, Origin: "brief", Kind: "spec-gap", FoundBy: "review", Summary: "c"},
		},
		Recorded: []defect.Defect{
			{ID: "z", Kind: "bug", Origin: "work", FoundBy: "operator", Summary: "zed"},
			{ID: "a", Kind: "bug", Origin: "work", FoundBy: "operator", Summary: "ay"},
		},
	})
	for _, want := range []string{
		"## Run record\n\nGenerated by vloop brief close on 2026-01-02. Recompute with: vloop metrics B1.loop-brief\n\n```\nB1  ",
		"- B1/i2-gate — bug, work, found by gate: gate failed\n- B1/i3-review-1 — bug, work, found by review: b\n- B1/i3-review-2 — spec-gap, brief, found by review: c\n- a — bug, work, found by operator: ay\n- z — bug, work, found by operator: zed\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in:\n%s", want, got)
		}
	}
	if strings.Count(got, "```") != 4 || !strings.Contains(got, "id  ") {
		t.Fatalf("want two fenced blocks, the second the task table:\n%s", got)
	}
}

func TestSnapshotWrite(t *testing.T) {
	root := t.TempDir()
	r := fixtureReport(t)
	rel, err := WriteSnapshot(root, r)
	if err != nil {
		t.Fatal(err)
	}
	if rel != ".vloop/state/metrics/"+r.RunID+".json" {
		t.Fatalf("path %q", rel)
	}
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	if !strings.HasSuffix(s, "}\n") || !strings.HasPrefix(s, "{\n  \"schema\": \"metrics/v1\",\n") {
		t.Fatalf("not 2-space indented with trailing newline:\n%s", s)
	}
	v, err := schema.Validate(metrics.Schema, data)
	if err != nil || len(v) > 0 {
		t.Fatalf("snapshot does not validate: %v %v", err, v)
	}
}
